import { Header } from '@/components/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Footer } from '@/components/Footer'
import AuthProvider from '@/components/Admin/Auth/AuthProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <Header/>
        
<AuthProvider>

        {children}
</AuthProvider>
        <Footer/></body>
    </html>
  )
}
