import { CallToActions } from "@/components/Call-to-actions"
import { Contact } from "@/components/Contact"
import { DevelopperWeb } from "@/components/DevelopperWeb"
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function Home() {
    return (
        <main className="">
            <CallToActions />
            <DevelopperWeb />
            <Contact />
        </main>
    )
}
