import { Metadata } from "next"
import React from "react"

export const metadata: Metadata = {
    title: "NSWeb Admin",
    description: "Generated by create next app",
}
export default function Admin() {
    return <div></div>
}
