import { Metadata } from "next"
import React from "react"

export const metadata: Metadata = {
    title: "Mon Blog",
    description: "Generated by create next app",
}

export default function Blog() {
    return <div>page</div>
}
